apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-initdb-config
data:
  AIRFLOW_HOME: /opt/airflow
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://postgres:postgres@airflow-db-executor:5432/postgres
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: 'true'
  AIRFLOW__CORE__REMOTE_LOGGING: 'false'
  AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: /opt/airflow/pod_templates/airflow-worker-based.yaml
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__WEBSERVER__AUTHENTICATE: 'true'
  AIRFLOW__WEBSERVER__AUTH_BACKEND: airflow.contrib.auth.backends.password_auth
  AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
  # Supply your container worker image here, either selfbuilt "airflow image" with dags or apache/airflow
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: 'kubegut/airflowk8sdemo'
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 'latest'
  AIRFLOW__KUBERNETES__NAMESPACE: default
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: default
  AIRFLOW__KUBERNETES__IN_CLUSTER: 'true'
  AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: 'true'
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/log
  AIRFLOW__LOGGING__REMOTE_LOGGING: 'false'